export enum USERS {
  USERS_READ = 'USERS_READ',
  USERS_WRITE = 'USERS_WRITE',
  USERS_DELETE = 'USERS_DELETE',
}
export enum DEPARTMENTS {
  DEPARTMENTS_READ = 'DEPARTMENTS_READ',
  DEPARTMENTS_WRITE = 'DEPARTMENTS_WRITE',
  DEPARTMENTS_DELETE = 'DEPARTMENTS_DELETE',
}
export enum PERIODS {
  PERIODS_READ = 'PERIODS_READ',
  PERIODS_WRITE = 'PERIODS_WRITE',
  PERIODS_DELETE = 'PERIODS_DELETE',
}
export enum ROLES {
  ROLES_READ = 'ROLES_READ',
  ROLES_WRITE = 'ROLES_WRITE',
  ROLES_DELETE = 'ROLES_DELETE',
}

export enum GLOBAL_SETTINGS {
  GLOBAL_SETTINGS_READ = 'GLOBAL_SETTINGS_READ',
  GLOBAL_SETTING_UPDATE = 'GLOBAL_SETTING_UPDATE',
}
export enum MAILING_LIST {
  MAILING_LIST_READ = 'MAILING_LIST_READ',
  MAILING_LIST_DELETE = 'MAILING_LIST_DELETE',
  MAILING_LIST_WRITE = 'MAILING_LIST_WRITE',
}

export type ADMIN =
  | USERS
  | ROLES
  | DEPARTMENTS
  | PERIODS
  | GLOBAL_SETTINGS
  | MAILING_LIST;
